language: python
sudo: false
python:
  - "2.6"
  - "2.7"
os:
  - osx
  - linux
env:
  - CYTHON=0
  - CYTHON=1
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-2.6.txt; fi
  - if [[ $CYTHON == 1 ]]; then pip install cython; fi
script:
  - python setup.py test
