language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install psutil
  - pip install unittest2
  - python setup.py develop
# command to run tests
script: unit2 -v discover
