language: python
python:
  - "2.6"
  - "2.7"
env:
  - CYTHON = true
  - CYTHON = false
install:
  - pip install psutil
  - pip install unittest2
  - if [[ $CYTHON == true ]]; then pip install cython; fi
  - python setup.py develop
# command to run tests
script: unit2 discover
