language: python
python:
  - "2.6"
  - "2.7"
env:
  - CYTHON=0
  - CYTHON=1
install:
  - pip install psutil
  - pip install unittest2
  - if [[ $CYTHON == 1 ]]; then pip install cython; fi
  - python setup.py develop
script: unit2 discover
