build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path
install:
  - ps: pip install psutil
  - ps: pip install unittest2
test_script:
  - ps: python setup.py test