build: false
environment:
  - PYTHON: "C:/Python27"
init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - ps: python C:/get-pip.py
  - ps: pip install psutil
test_script:
  - ps: python setup.py test